version: "3.8"

services:
  gh-deploy:
    image: registry:5000/gh-deploy
    build:
      context: ./swarm-gh-autodeploy
      dockerfile: arm.Dockerfile
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /path/to/images:/mounted/volume:ro
      - /path/to/setup.json:/root/setup.json:ro
    deploy:
      placement:
        constraints:
          - "node.labels.adm==true"
          - "node.role==manager"
